// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"Go/student"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initStudentAPI(db *gorm.DB) student.StudentAPI {
	studentRepository := student.ProvideStudentRepository(db)
	studentService := student.ProvideStudentService(studentRepository)
	studentAPI := student.ProvideStudentAPI(studentService)
	return studentAPI
}
